"""Added date time, status and error columns to promptmodel

Revision ID: 25bdb0f6f41e
Revises: f1e65f93f678
Create Date: 2025-04-03 21:51:23.220140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25bdb0f6f41e'
down_revision: Union[str, None] = 'f1e65f93f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promptmodel', sa.Column('add_time', sa.Integer(), nullable=True))
    op.add_column('promptmodel', sa.Column('start_time', sa.Integer(), nullable=True))
    op.add_column('promptmodel', sa.Column('finish_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promptmodel', 'finish_time')
    op.drop_column('promptmodel', 'start_time')
    op.drop_column('promptmodel', 'add_time')
    # ### end Alembic commands ###
