"""Changed promptmodel to conversation and added messages

Revision ID: 354ab59d617d
Revises: 25bdb0f6f41e
Create Date: 2025-04-23 15:36:53.646142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '354ab59d617d'
down_revision: Union[str, None] = '25bdb0f6f41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referenced_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messagemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.Integer(), nullable=False),
    sa.Column('request_tokens', sa.Integer(), nullable=True),
    sa.Column('response_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('promptmodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptmodel',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prompt', mysql.TEXT(), nullable=True),
    sa.Column('referenced_by', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('request_tokens', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('response_tokens', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('response', mysql.LONGTEXT(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('error', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('add_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('start_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('finish_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('messagemodel')
    op.drop_table('conversationmodel')
    # ### end Alembic commands ###
