"""initial

Revision ID: 522036f2bba4
Revises: 
Create Date: 2025-04-01 21:09:31.882403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '522036f2bba4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', mysql.TEXT(), nullable=True),
    sa.Column('referenced_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_tokens', sa.Integer(), nullable=True),
    sa.Column('response_tokens', sa.Integer(), nullable=True),
    sa.Column('response', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promptmodel')
    # ### end Alembic commands ###
