"""Added conversation memory columns

Revision ID: 9dc4b7131522
Revises: 354ab59d617d
Create Date: 2025-04-23 17:27:52.037311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9dc4b7131522'
down_revision: Union[str, None] = '354ab59d617d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationmodel', sa.Column('all_messages', sa.BLOB(), nullable=True))
    op.add_column('conversationmodel', sa.Column('new_messages', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversationmodel', 'new_messages')
    op.drop_column('conversationmodel', 'all_messages')
    # ### end Alembic commands ###
